<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>1.0.0-preview.2</Version>
    <AssemblyName>CommunityToolkit.VectorData.Pinecone</AssemblyName>
    <RootNamespace>$(AssemblyName)</RootNamespace>
    <TargetFrameworks>net10.0;net8.0;netstandard2.0;net462</TargetFrameworks>
    <IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">true</IsAotCompatible>

    <Title>Pinecone provider for Microsoft.Extensions.VectorData</Title>
    <Description>Pinecone provider for Microsoft.Extensions.VectorData by the .NET Community Toolkit</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pinecone.Client" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.AI.Abstractions" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' Or '$(TargetFramework)' == 'net462' ">
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CommunityToolkit.VectorData.Pinecone.UnitTests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

</Project>
