<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>1.0.0-preview.1</Version>
    <AssemblyName>CommunityToolkit.VectorData.Chroma</AssemblyName>
    <RootNamespace>$(AssemblyName)</RootNamespace>
    <TargetFrameworks>net10.0;net8.0;netstandard2.0;net462</TargetFrameworks>
    <IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">true</IsAotCompatible>

    <Title>Chroma provider for Microsoft.Extensions.VectorData</Title>
    <Description>Chroma provider for Microsoft.Extensions.VectorData by the .NET Community Toolkit</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Linq.AsyncEnumerable" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.AI.Abstractions" />
    <PackageReference Include="ChromaDotNet.Client" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CommunityToolkit.VectorData.Chroma.UnitTests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

</Project>
