<Project Sdk="Microsoft.NET.Sdk">
  
  <PropertyGroup>
    <!-- THIS PROPERTY GROUP MUST COME FIRST -->
    <Version>1.0.0</Version>
    <AssemblyName>CommunityToolkit.VectorData.Weaviate</AssemblyName>
    <RootNamespace>$(AssemblyName)</RootNamespace>
    <TargetFrameworks>net10.0;net8.0;netstandard2.0;net462</TargetFrameworks>
    <!-- <IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">true</IsAotCompatible> -->

    <Title>Weaviate provider for Microsoft.Extensions.VectorData</Title>
    <Description>Weaviate provider for Microsoft.Extensions.VectorData by the .NET Community Toolkit</Description>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="System.Linq.AsyncEnumerable" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.AI.Abstractions" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' Or '$(TargetFramework)' == 'net462' ">
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CommunityToolkit.VectorData.Weaviate.UnitTests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

</Project>