<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;$(NetFrameworkTfm)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <AssemblyName>CommunityToolkit.VectorData.SqlServer.ConformanceTests</AssemblyName>
    <RootNamespace>SqlServer.ConformanceTests</RootNamespace>
    <UserSecretsId>b7762d10-e29b-4bb1-8b74-b6d69a667dd4</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <!-- The HybridSearch tests require running against Azure SQL -->
    <Compile Remove="SqlServerHybridSearchTests.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
    <PackageReference Include="Microsoft.Extensions.VectorData.ConformanceTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SqlServer\SqlServer.csproj" />
  </ItemGroup>

</Project>
