<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>1.0.0-preview.3</Version>
    <AssemblyName>CommunityToolkit.VectorData.Redis</AssemblyName>
    <RootNamespace>$(AssemblyName)</RootNamespace>
    <TargetFrameworks>net10.0;net8.0;netstandard2.0;net462</TargetFrameworks>

    <Title>Redis provider for Microsoft.Extensions.VectorData</Title>
    <Description>Redis provider for Microsoft.Extensions.VectorData by the .NET Community Toolkit</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.AI.Abstractions" />
    <PackageReference Include="NRedisStack" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CommunityToolkit.VectorData.Redis.UnitTests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

</Project>