<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0;$(NetFrameworkTfm)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTestProject>true</IsTestProject>
    <IsPackable>false</IsPackable>
    <RootNamespace>Qdrant.ConformanceTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Testcontainers.Qdrant" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\src\Qdrant\Qdrant.csproj" />
    <PackageReference Include="Microsoft.Extensions.VectorData.ConformanceTests" />
  </ItemGroup>

</Project>
